Cherry-picked commit with merge conflict

diff --git a/.github/actions/setup-rocm/action.yml b/.github/actions/setup-rocm/action.yml
--- a/.github/actions/setup-rocm/action.yml
+++ b/.github/actions/setup-rocm/action.yml
@@ -59,6 +59,14 @@ runs:
             echo "$msg"
             exit 1
         fi
+<<<<<<< HEAD
+=======
+        if [[ $ngpu -eq 1 ]]; then
+            echo "Error: only 1 GPU detected, at least 2 GPUs are needed for distributed jobs"
+            echo "$msg"
+            exit 1
+        fi
+>>>>>>> 5729657180 ([ROCm] Specialized binary elementwise broadcast kernel for mixed dtypes with float/bfloat16/half (#2791))
 
     - name: Runner diskspace health check
       uses: pytorch/pytorch/.github/actions/diskspace-cleanup@main
